destination: ./_deploy
lsi: false
highlighter: pygments
markdown: kramdown
permalink: /:categories/:year/:title.html 

exclude: ['README.md', 'LICENSE.md', '.gitignore', '.git', 'bitbucket-pipelines.yml']
