 image: summerisgone/jekyll_s3_website

 pipelines:
   default:
     - step:
         script:
           - cd $BITBUCKET_CLONE_DIR; jekyll b
           - export AWS_ACCESS_KEY_ID="$S3_ID"
           - export AWS_SECRET_ACCESS_KEY="$S3_SECRET"
           - cd $BITBUCKET_CLONE_DIR; aws --region us-west-1 s3 sync --delete _deploy s3://linuxalt-com/ --exclude '.git/*'